### ISSUE TITLE
404 en secciones de portada

### ISSUE THREAD

**Issue by DaFeBa** [gulBAC/gulBAC-oldsite#2]
Las secciones del sitio:

Movimiento GNU y FSF, Licencias y Backend Dan un error 404.

**Comment by comtom** [comment]
Las secciones no estan escritas. Habria que volcarlas al wiki y luego con el formato correspondiente pasarlas a hyde, nuestro sistema de generacion sincronico del sitio.

Propongo que en [1] anotemos cada una de ellas (salvo backend ya que esta seccion sera un sistema para cargar y obtener datos hecho en django)

[1] http://wiki.gulbac.org.ar/index.php/Proyecto_gulBAC_3.0#Secciones_pendientes
