### ISSUE TITLE
[propuesta] cambiar imagen logo.png

### ISSUE THREAD

**Issue by DaFeBa** [gulBAC/gulBAC-oldsite#3]
La imagen en la esquina superior izquierda no es demasiado legible, y el color del fondo se mimetiza con la esfera verde. Esta es una idea de una imagen que con fondo más claro que continúe la torma del panel superior.

imagen actual
http://gulbac.org.ar/media/img/logo.png

imagen propuesta
http://wiki.gulbac.org.ar/images/8/8d/Logo-v3.png

**Comment by comtom** [comment]
Te llevaria mucho hacer un screenshot para mostrarle a todos y que luego lo subamos al wiki para armar una votacion?

**Comment by DaFeBa** [comment]
Ahí hice la comparativa:

http://wiki.gulbac.org.ar/images/0/04/Mockup01.png

**Comment by DaFeBa** [comment]
otra variante, haciendo el logo 2 pixels más algo, ocupando las dos bandas, y una alternativa verde oscuro con texto claro.

http://wiki.gulbac.org.ar/images/7/72/Boceto.jpg
