### ISSUE TITLE
Sitio de suscripcion a la lista

### ISSUE THREAD

**Issue by comtom** [gulBAC/gulBAC-oldsite#6]
Hay errores en los links a CSS e imagenes. Habria que editar el HTML y actualizar links y dejarlo como el sitio nuevo.

Me refiero al la siguiente URL:
https://listas.linux.org.ar/cgi-bin/mailman/listinfo/gulbac

**Comment by tincho** [comment]
El 08/06/11 21:37, comtom escribió:

> Hay errores en los links a CSS e imagenes. Habria que editar el HTML y actualizar links y dejarlo como el sitio nuevo.
> 
> Me refiero al la siguiente URL:
> https://listas.linux.org.ar/cgi-bin/mailman/listinfo/gulbac

Lo se, pero al intentar editar eso desde la interfaz web (lo quise
arreglar hace casi un mes), incluso sin modificar nada el mailman dice
que el código html es inválido y no se puede submittear.
Seguramente lo subieron a mano desde otro lado, habría que pedirle a
dererk o alguien de USLA que nos deje modificarlo a manopla
Saludos

**Comment by comtom** [comment]
Creo que nicoman lo hizo en su momento. Pregunto entonces en la lista miembros a ver si nos pueden dar una mano.

**Comment by comtom** [comment]
Avise a la gente de USLA. Quedaron en que van a migrar las listas a otro server. Pueden seguir el siguiente thread por mas novedades (necesitan estar suscriptos a la lista para ver los mensajes).

https://listas.usla.org.ar/cgi-bin/mailman/private/miembros/2011-June/002003.html
